### ISSUE TITLE
improve error handling

### ISSUE THREAD

**Issue by hyde404** [badjware/gitlabfs#1]
Hello,

I get an issue when I try to reach gitlab without token.
Here's the error I get : 

Started git cloner worker routine
Started git cloner worker routine
Started git cloner worker routine
Started git cloner worker routine
Started git cloner worker routine
Started git puller worker routine
Started git puller worker routine
Started git puller worker routine
Started git puller worker routine
Started git puller worker routine
root group fetch fail: failed to fetch group with id 7141: GET https://gitlabxxxxxxx/api/v4/groups/7141: 404 {message: 404 Group Not Found}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7f1a15]

We should get an 403 not authorized error instead.

Cheers

**Comment by badjware** [comment]
Should be fixed in the most recent version.

run `go get -u github.com/badjware/gitlabfs` to update to the latest version.

Let me know if there is any issue.
