### ISSUE TITLE
Fetch wildcard

### ISSUE THREAD

**Issue by r0mdau** [badjware/gitlabfs#10]
Current :

```
[remote "origin"]
    url = git@gitlab.com:myorg/repo.git
    fetch = +refs/heads/master:refs/remotes/origin/master
```

The `fetch` property is only fetching the `master branch` and I would like to be allowed to fetch other branches.

Wanted :

```
[remote "origin"]
    url = git@gitlab.com:myorg/repo.git
    fetch = +refs/heads/*:refs/remotes/origin/*
```

With this configuration, you can then run `git fetch` and checkout the remote branches locally.

**Comment by r0mdau** [comment]
I think this is related with #7 , this current fetch is set because using the `--depth` git flag.

And for this to work on WSL2, I have set a depth of 1 000 000 in my gitlabfs config 😄

**Comment by badjware** [comment]
Is this still an issue? I tried, but was unable to reproduce this behavior.

**Comment by r0mdau** [comment]
I upgraded to Ubuntu 22 and think it is not an issue anymore because of the git upgraded version
